# Makefile for Program 1myHello: Extrema.class
	echo Main-class: Extrema > Manifest
	jar cvfm myExtrema Manifest Extrema.class
	rm Manifest
	chmod +x myHelloExtrema.class: Extrema.java
	javac -Xlint Extrema.javaclean:
	rm -f Extrema.class myExtremasubmit: README makefile Extrema.java
	submit cmps012b-pt.u13 pa1 README makefile Extrema.java